version: '3'

services:

  quick:
    build: .
    ports:
      - "9999:9999"
    env_file:
      - variables.env

  pgadmin:
    image: elestio/pgadmin
    restart: always
    env_file:
      - variables.env
    ports:
       - "8080:8080"
    volumes:
        - ./servers.json:/pgadmin4/servers.json
